/* ====== SPAN MACROS ====== */
#define SPAN_ALERT(string) ("<span class='alert'>" + string + "</span>")
#define SPAN_COMBAT(string) ("<span class='combat'>" + string + "</span>")
#define SPAN_NOTICE(string) ("<span class='notice'>" + string + "</span>")
#define SPAN_INTERNAL(string) ("<span class='internal'>" + string + "</span>")
#define SPAN_MEDAL(string) ("<span class='medal'>" + string + "</span>")
#define SPAN_ADMIN(string) ("<span class='admin'>" + string + "</span>")
#define SPAN_SUCCESS(string) ("<span class='success'>" + string + "</span>")
#define SPAN_SUBTLE(string) ("<span class='subtle'>" + string + "</span>")
#define SPAN_NAME(string) ("<span class='name'>" + string + "</span>")
#define SPAN_MESSAGE(string) ("<span class='message'>" + string + "</span>")
#define SPAN_PREFIX(string) ("<span class='prefix'>" + string + "</span>")
#define SPAN_EMOTE(string) ("<span class='emote'>" + string + "</span>")
#define SPAN_VGA(string) ("<span class='vga'>" + string + "</span>")
#define SPAN_HINT(string) ("<span class='hint'>" + string + "</span>")
#define SPAN_SUBTITLE(string) ("<span class='subtitle'>" + string + "</span>")
#define SPAN_GOOD(string) ("<span class='good'>" + string + "</span>")
#define SPAN_BAD(string) ("<span class='bad'>" + string + "</span>")
#define SPAN_BOLD(string) ("<span class='bold'>" + string + "</span>")
#define SPAN_ITALIC(string) ("<span class='italic'>" + string + "</span>")
#define SPAN_FLOCKSAY(string) ("<span class='flocksay'>" + string + "</span>")
#define SPAN_GAME(string) ("<span class='game'>" + string + "</span>")
#define SPAN_BANREASON(string) ("<span class='banreason'>" + string + "</span>")
#define SPAN_TOOLTIPTEXT(string) ("<span class='tooltiptext'>" + string + "</span>")
#define SPAN_PR_NUMBER(string) ("<span class='pr_number'>" + string + "</span>")
#define SPAN_HELPMSG(string) ("<span class='helpmsg'>" + string + "</span>")
#define SPAN_WARNING(string) ("<span class='warning'>" + string + "</span>")
#define SPAN_NOTIFICATION(string) ("<span class='notification'>" + string + "</span>")
#define SPAN_BLOBALERT(string) ("<span class='blobalert'>" + string + "</span>")
#define SPAN_INFO(string) ("<span class='info'>" + string + "</span>")
#define SPAN_REGULAR(string) ("<span class='regular'>" + string + "</span>")
#define SPAN_MONOSPACE(string) ("<span class='monospace'>" + string + "</span>")

#define SPAN_RAINBOW(string) ("<span class='rainbow'>" + string + "</span>")

// Intents
#define SPAN_HELP(string) ("<span class='help'>" + string + "</span>")
#define SPAN_DISARM(string) ("<span class='disarm'>" + string + "</span>")
#define SPAN_GRAB(string) ("<span class='grab'>" + string + "</span>")
#define SPAN_HARM(string) ("<span class='harm'>" + string + "</span>")

// OOC / LOOC
#define SPAN_ADMINOOC(string) ("<span class='adminooc'>" + string + "</span>")

// Helps
#define SPAN_MHELP(string) ("<span class='mhelp'>" + string + "</span>")
#define SPAN_AHELP(string) ("<span class='ahelp'>" + string + "</span>")
