##### Labeler ##########################################################################################################
# Enable "labeler" for your PR that would add labels to PRs based on the paths that are modified in the PR.
labelPRBasedOnFilePath:

  # Add 'mapping' label to any changes within 'maps' folder or any subfolders
  A-Mapping:
    - maps/**/*
    - '**/*.dmm'

  # Add 'tooling' label to any changes to the .github folder or any subfolders
  A-Tooling:
    - .github/**/*
    - 'tools/**/*'

  # Add 'tgui' label to any changes to the tgui folder or any subfolders
  A-UI:
    - tgui/**/*

  # Add 'documentation' label to any changes to a .md file
  C-Documentation:
    - '**/*.md'

  # Add 'sound' label to any changes within 'sound' folder or any subfolders
  C-Sound:
    - sound/**/*
    - '**/*.ogg'

  # Add 'sprites' label to any changes within 'icons' folder or any subfolders
  C-Sprites:
    - icons/**/*
    - '**/*.dmi'
