##### Labeler ##########################################################################################################
# Enable "labeler" for your PR that would add labels to PRs based on the paths that are modified in the PR.
labelPRBasedOnFilePath:
  # Add 'sprites' label to any changes within 'icons' folder or any subfolders
  sprites:
    - icons/**/*
    - '**/*.dmi'

  # Add 'mapping' label to any changes within 'maps' folder or any subfolders
  mapping:
    - maps/**/*
    - '**/*.dmm'

  # Add 'documentation' label to any changes to a .md file
  documentation:
    - '**/*.md'

  # Add 'github' label to any changes to the .github folder or any subfolders
  github:
    - .github/**/*
