# A mapping of keyword aliases to event type. Form of match:action name.
# Required.
aliasMappings:
  "/rebuild tgui": "rebuild-tgui"
  "/rebuild-tgui": "rebuild-tgui"

# Determines if alias matching is case sensitive.
# Optional. Defaults to true.
caseSensitive: true

# A mapping of action names to user group permissions.
# Form of event type:group name or combined names (Explained lower in the README).
# Optional, defaults to MEMBER for each.
permissionMappings:
  "rebuild-tgui": [MEMBER, CONTRIBUTOR, PRAUTHOR]
