# A mapping of keyword aliases to event type. Form of match:event type.
# Required.
aliasMappings:
  "/rebuild tgui": "rebuild-tgui"
  "/rebuild-tgui": "rebuild-tgui"

# Determines if alias matching is case sensitive.
# Optional. Defaults to true.
caseSensitive: false

# A mapping of event types to user group permissions.
# Form of event type:group name or combined names (Explained lower in the README).
# Optional, defaults to MEMBER for each.
permissionMappings:
  "rebuild-tgui": [MEMBER, COLLABORATOR, PRAUTHOR]
