BYOND_MAJOR_VERSION=516
BYOND_MINOR_VERSION=1687

# SpacemanDMM reference: release tag or commit SHA
SPACEMAN_DMM_REF=suite-1.11

# See: goonstation/rust-g - is the tag for the release
RUST_G_VERSION=v7.0.0-G

NODE_VERSION=24

# Python version for mapmerge and other tools
PYTHON_VERSION=3.12.0
