CREATE_NAMESPACE(ATMOS)

ADD_TO_NAMESPACE(ATMOS)(var/const/HEAT_CAPACITIES = alist(
	GAS_OXYGEN = 40,
	GAS_NITROGEN = 50,
	GAS_CARBON_DIOXIDE = 40,
	GAS_TOXINS = 150,
	GAS_FARTS = 69,
	GAS_RADGAS = 5,
	GAS_NITROUS_OXIDE = 60,
	GAS_AGENT_B = 300,
))
