/// For chemical stuff
CREATE_NAMESPACE(CHEM)

/// REQUESTS
CREATE_NAMESPACE(CHEM, REQUEST)

/// Different stages of chemical requests
CREATE_NAMESPACE(CHEM, REQUEST, STATE)
ADD_TO_NAMESPACE(CHEM, REQUEST, STATE)(var/const/PENDING = "pending")
ADD_TO_NAMESPACE(CHEM, REQUEST, STATE)(var/const/DENIED = "denied")
ADD_TO_NAMESPACE(CHEM, REQUEST, STATE)(var/const/FULFILLED = "fulfilled")

CREATE_NAMESPACE(CHEM, REQUEST, AMOUNT)
ADD_TO_NAMESPACE(CHEM, REQUEST, AMOUNT)(var/const/MAX = 400)
