CREATE_NAMESPACE(CUSTOMIZATION)

/// The gender which is TYPICALLY assigned to this customization style.
/// Primarily for character appearance randomization.
CREATE_NAMESPACE(CUSTOMIZATION, GENDER)
ADD_TO_NAMESPACE(CUSTOMIZATION, GENDER)(var/const/MASCULINE = (1 << 0))
ADD_TO_NAMESPACE(CUSTOMIZATION, GENDER)(var/const/FEMININE = (1 << 1))

/// Customization style slots.
CREATE_NAMESPACE(CUSTOMIZATION, SLOT)
ADD_TO_NAMESPACE(CUSTOMIZATION, SLOT)(var/const/HAIR = 1)

/// Hair customization style types.
CREATE_NAMESPACE(CUSTOMIZATION, HAIR)
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/SHORT = "hair_short")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/LONG = "hair_long")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/HAIRUP = "hair_hairup")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/GIMMICK = "hair_gimmick")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/FACIAL = "hair_facial")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/EYEBROWS = "hair_eyebrows")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/MAKEUP = "hair_makeup")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/BIOLOGICAL = "hair_biological")

/// Be sure to mirror this to the existing `CUSTOMIZATION::SLOT`s.
ADD_TO_NAMESPACE(CUSTOMIZATION)(var/alist/type_to_slot = alist(
	CUSTOMIZATION::HAIR::SHORT		= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::LONG		= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::HAIRUP		= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::GIMMICK	= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::FACIAL		= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::EYEBROWS	= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::MAKEUP		= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::BIOLOGICAL	= CUSTOMIZATION::SLOT::HAIR,
))

/// For list sorting. Weights default to 0 if not defined here.
ADD_TO_NAMESPACE(CUSTOMIZATION)(var/alist/type_weights = alist(
	CUSTOMIZATION::HAIR::SHORT		= 1,
	CUSTOMIZATION::HAIR::LONG		= 2,
	CUSTOMIZATION::HAIR::HAIRUP		= 3,
	CUSTOMIZATION::HAIR::GIMMICK	= 4,
	CUSTOMIZATION::HAIR::FACIAL		= 5,
	CUSTOMIZATION::HAIR::EYEBROWS	= 6,
	CUSTOMIZATION::HAIR::MAKEUP		= 7,
	CUSTOMIZATION::HAIR::BIOLOGICAL	= 8,
))
