CREATE_NAMESPACE(CUSTOMIZATION)

/// The gender which is TYPICALLY assigned to this customization style.
/// Primarily for character appearance randomization.
CREATE_NAMESPACE(CUSTOMIZATION, GENDER)
ADD_TO_NAMESPACE(CUSTOMIZATION, GENDER)(var/const/MASCULINE = (1 << 0))
ADD_TO_NAMESPACE(CUSTOMIZATION, GENDER)(var/const/FEMININE = (1 << 1))

/// Customization style slots.
CREATE_NAMESPACE(CUSTOMIZATION, SLOT)
ADD_TO_NAMESPACE(CUSTOMIZATION, SLOT)(var/const/HAIR = "hair")

/// Hair customization style types.
CREATE_NAMESPACE(CUSTOMIZATION, HAIR)
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/HAIRHEAD = "hair_head")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/FACIAL = "hair_facial")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/EYEBROWS = "hair_eyebrows")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/MAKEUP = "hair_makeup")
ADD_TO_NAMESPACE(CUSTOMIZATION, HAIR)(var/const/BIOLOGICAL = "hair_biological")

/// Be sure to mirror this alist to the existing `CUSTOMIZATION::SLOT`s.
ADD_TO_NAMESPACE(CUSTOMIZATION)(var/alist/types_to_slot = alist(
	CUSTOMIZATION::HAIR::HAIRHEAD 	= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::FACIAL 	= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::EYEBROWS 	= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::MAKEUP		= CUSTOMIZATION::SLOT::HAIR,
	CUSTOMIZATION::HAIR::BIOLOGICAL	= CUSTOMIZATION::SLOT::HAIR,
))
