/// Default colours for mapping helpers.
CREATE_NAMESPACE(HELPER_COLOR)

ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/CARGO = "#f7e43d")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/COMMAND = "#00783c")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/ENGINEERING = "#f7af3d")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/MAINTENANCE = "#e5ff32")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/MEDICAL = "#3daff7")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/MORGUE = "#002135")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/RESEARCH = "#b23df7")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/TOXINS = "#a3f73d")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/SECURITY = "#f73d3d")
ADD_TO_NAMESPACE(HELPER_COLOR)(var/const/SPECIAL = "#ffa135")
