/// Namespace for all things manufacturers
CREATE_NAMESPACE(MANUFACTURER)

/// The ui categories of the blueprints
CREATE_NAMESPACE(MANUFACTURER, CATEGORY)

ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/TOOL = "Tool")
ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/CLOTHING = "Clothing")
ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/RESOURCE = "Resource")
ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/COMPONENT = "Component")
ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/ORGAN = "Organ")
ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/MACHINERY = "Machinery")
ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/MEDICINE = "Medicine")
ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/MISCELLANEOUS = "Miscellaneous")
ADD_TO_NAMESPACE(MANUFACTURER, CATEGORY)(var/const/DOWNLOADED = "Downloaded")


/// needs hardocded list instead of _get_namespace_constants() because we need the list at compile time, you must add it to here when you add a category!
// ADD_TO_NAMESPACE(MANUFACTURER)(var/list/CATEGORIES_LIST = list(
// 	MANUFACTURER::CATEGORY::TOOL,
// 	MANUFACTURER::CATEGORY::CLOTHING,
// 	MANUFACTURER::CATEGORY::RESOURCE,
// 	MANUFACTURER::CATEGORY::COMPONENT,
// 	MANUFACTURER::CATEGORY::ORGAN,
// 	MANUFACTURER::CATEGORY::MACHINERY,
// 	MANUFACTURER::CATEGORY::MEDICINE,
// 	MANUFACTURER::CATEGORY::MISCELLANEOUS,
// 	MANUFACTURER::CATEGORY::DOWNLOADED,
// ))

