CREATE_NAMESPACE(MATERIAL)

/// Constants used to set material amounts in relative terms
CREATE_NAMESPACE(MATERIAL, AMOUNT)

ADD_TO_NAMESPACE(MATERIAL, AMOUNT)(var/const/TILE = 0.025)
ADD_TO_NAMESPACE(MATERIAL, AMOUNT)(var/const/ROD = 0.05)
ADD_TO_NAMESPACE(MATERIAL, AMOUNT)(var/const/SHEET = 0.1)
ADD_TO_NAMESPACE(MATERIAL, AMOUNT)(var/const/DEFAULT = 1)
