CREATE_NAMESPACE(MATERIAL)

/// Constants used to set material amounts in relative terms
CREATE_NAMESPACE(MATERIAL, AMOUNT)
ADD_TO_NAMESPACE(MATERIAL, AMOUNT)(var/const/TILE = 0.025)
ADD_TO_NAMESPACE(MATERIAL, AMOUNT)(var/const/ROD = 0.05)
ADD_TO_NAMESPACE(MATERIAL, AMOUNT)(var/const/SHEET = 0.1)
ADD_TO_NAMESPACE(MATERIAL, AMOUNT)(var/const/DEFAULT = 1)

/// IDs of various material properties
CREATE_NAMESPACE(MATERIAL, PROPERTY)
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/CHEM_RESIST = "chemical")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/DENSITY = "density")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/ELECTRIC_COND = "electrical")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/FLAMMABLE = "flammable")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/HARDNESS = "hard")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/MELTING_POINT = "melting_point")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/RADS = "radioactive")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/RADS_NEUTRON = "n_radioactive")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/REFLECT = "reflective")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/THERMAL_COND = "thermal")

ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/GAS_MOLITZ = "molitz_bubbles")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/GAS_PLASMA = "plasma_offgas")
ADD_TO_NAMESPACE(MATERIAL, PROPERTY)(var/const/PLUTONIUM = "spent_fuel")
