CREATE_NAMESPACE(MATERIAL)

ADD_TO_NAMESPACE(MATERIAL)(var/const/AMOUNT_TILE = 0.025)
ADD_TO_NAMESPACE(MATERIAL)(var/const/AMOUNT_ROD = 0.05)
ADD_TO_NAMESPACE(MATERIAL)(var/const/AMOUNT_SHEET = 0.1)
ADD_TO_NAMESPACE(MATERIAL)(var/const/AMOUNT_DEFAULT = 1)
