/// Customization layers.
CREATE_NAMESPACE(CUSTOMIZATION, LAYER)
ADD_TO_NAMESPACE(CUSTOMIZATION, LAYER)(var/const/HAIR_BOTTOM = "hair_bottom")
ADD_TO_NAMESPACE(CUSTOMIZATION, LAYER)(var/const/HAIR_MIDDLE = "hair_middle")
ADD_TO_NAMESPACE(CUSTOMIZATION, LAYER)(var/const/HAIR_TOP = "hair_top")
