#define TEAM_BASED_ROUND_REQUIREMENT 5

#define ANTAGONIST_SOURCE_ROUND_START null
#define ANTAGONIST_SOURCE_LATE_JOIN "late-joining "
#define ANTAGONIST_SOURCE_RANDOM_EVENT "random event "
#define ANTAGONIST_SOURCE_ADMIN "admin-created "
#define ANTAGONIST_SOURCE_MUTANT "antag-mutantrace "
#define ANTAGONIST_SOURCE_SUMMONED "antag-summoned "
#define ANTAGONIST_SOURCE_CONVERTED "antag-converted "
#define ANTAGONIST_SOURCE_OTHER "other "

#define ANTAGONIST_REMOVAL_SOURCE_DEATH "death"
#define ANTAGONIST_REMOVAL_SOURCE_OVERRIDE "override"
#define ANTAGONIST_REMOVAL_SOURCE_EXPIRED "expired"
#define ANTAGONIST_REMOVAL_SOURCE_SURGERY "surgery"

// wraith forms
#define WRAITH_FORM_DEFAULT 0
#define WRAITH_FORM_PLAGUEBRINGER 1
#define WRAITH_FORM_HARBINGER 2
#define WRAITH_FORM_TRICKSTER 3

// vampire power levels
#define VAMP_POWER_THERMAL_VISION 1
#define VAMP_POWER_XRAY_VISION 2
#define VAMP_POWER_MAXIMUM 3
