#define TEAM_BASED_ROUND_REQUIREMENT 5
#define ANTAGONIST_SOURCE_ROUNDSTART null
#define ANTAGONIST_SOURCE_LATEJOIN "late-joining "
#define ANTAGONIST_SOURCE_RANDOM_EVENT "random event "
#define ANTAGONIST_SOURCE_ADMIN null
