#define TEAM_BASED_ROUND_REQUIREMENT 5

#define ANTAGONIST_SOURCE_ROUND_START "round-start "
#define ANTAGONIST_SOURCE_LATE_JOIN "late-joining "
#define ANTAGONIST_SOURCE_RANDOM_EVENT "random event "
#define ANTAGONIST_SOURCE_ADMIN "admin-created "
#define ANTAGONIST_SOURCE_MUTANT "antag-mutantrace "
#define ANTAGONIST_SOURCE_SUMMONED "antag-summoned "
#define ANTAGONIST_SOURCE_CONVERTED "antag-converted "
#define ANTAGONIST_SOURCE_OTHER "other "

#define ANTAGONIST_REMOVAL_SOURCE_DEATH "death"
#define ANTAGONIST_REMOVAL_SOURCE_OVERRIDE "override"
#define ANTAGONIST_REMOVAL_SOURCE_EXPIRED "expired"
#define ANTAGONIST_REMOVAL_SOURCE_SURGERY "surgery"
