//Artemus REMOVAL


//#define DEBUG_ARTEMIS 1
//#define FORCE_ARTEMIS_MODE
//#define ARTEMIS_LINK_AT_ROUNDSTART

#define ASTEROID_BASIC_COUNT 8

#define PLANET_NUMPREFABS 1
#define PLANET_NUMPREFABSEXTRA 3

#define PLANET_MAPBORDER 1
