#define ARTIFACT_SIZE_LARGE 3
#define ARTIFACT_SIZE_MEDIUM 2
#define ARTIFACT_SIZE_TINY 1

// flags for allowed combinations
#define ARTIFACT_COMBINES_INTO_ANY (1<<0)
#define ARTIFACT_ACCEPTS_ANY_COMBINE (1<<1)
#define ARTIFACT_DOES_NOT_COMBINE (1<<2)
#define ARTIFACT_COMBINES_INTO_HANDHELD (1<<3)
#define ARTIFACT_COMBINES_INTO_LARGE (1<<4)
