#define EFFECT_TYPE_MUTANTRACE 1
#define EFFECT_TYPE_DISABILITY 2
#define EFFECT_TYPE_POWER 3
#define EFFECT_TYPE_FOOD 4

#define EFFECT_RESEARCH_NONE 0
#define EFFECT_RESEARCH_IN_PROGRESS 1
#define EFFECT_RESEARCH_DONE 2
#define EFFECT_RESEARCH_ACTIVATED 3
