#define CC_ERROR_INVALID_SX				1
#define CC_ERROR_INVALID_TX				2
#define CC_ERROR_INVALID_CONTAINER_SX	3
#define CC_ERROR_INVALID_CONTAINER_TX	4
#define CC_ERROR_INVALID_TEMPERATURE	5
#define CC_ERROR_CODE_PROTECTED			6
#define CC_ERROR_INSTRUCTION_LIMIT		7
#define CC_ERROR_INDEX_INVALID		8
#define CC_ERROR_MANUAL_ABORT			9

#define CC_NOTIFICATION_COMPLETE		101
#define CC_NOTIFICATION_SAVED			102

#define CC_STATUS_IDLE					1
#define CC_STATUS_RUNNING				2
