#define DMM_SUITE_VERSION 2

#define DMM_IGNORE_AREAS 1
#define DMM_IGNORE_TURFS 2
#define DMM_IGNORE_OBJS 4
#define DMM_IGNORE_NPCS 8
#define DMM_IGNORE_PLAYERS 16
#define DMM_IGNORE_MOBS 24
#define DMM_IGNORE_OVERLAYS 32
#define DMM_IGNORE_SPACE 64

#define DMM_OVERWRITE_MOBS (1 << 0)
#define DMM_OVERWRITE_OBJS (1 << 1)
#define DMM_BESPOKE_AREAS (1 << 2)
