#define MINDEATER_MAX_INTELLECT_THRESHOLD 100
#define MINDEATER_BRAIN_DMG_CAP BRAIN_DAMAGE_MAJOR
#define MINDEATER_INTELLECT_CHEM_INTERACTION 80

#define MINDEATER_DISGUISE_HUMAN "human"
#define MINDEATER_DISGUISE_COCKROACH "cockroach"
#define MINDEATER_DISGUISE_MOUSE "mouse"
