#define LANDMARK_PESTSTART "peststart"
#define LANDMARK_LATEJOIN "latejoin"
#define LANDMARK_NEW_PLAYER "new_player"
#define LANDMARK_MONKEY "monkey"
#define LANDMARK_BLOBSTART "blobstart"
#define LANDMARK_KUDZUSTART "kudzustart"
#define LANDMARK_SYNDICATE "Syndicate-Spawn"
#define LANDMARK_SYNDICATE_BOSS "SR Syndicate-Spawn"
#define LANDMARK_OBSERVER "Observer-Start"
#define LANDMARK_TWITCHY_BILL_RESPAWN "shitty_bill_respawn"
#define LANDMARK_PRISONWARP "prisonwarp"
#define LANDMARK_PRISONSECURITYWARP "prisonsecuritywarp"
