#define LANDMARK_PESTSTART "peststart"
#define LANDMARK_LATEJOIN "latejoin"
#define LANDMARK_NEW_PLAYER "new_player"
#define LANDMARK_MONKEY "monkey"
#define LANDMARK_BLOBSTART "blobstart"
#define LANDMARK_KUDZUSTART "kudzustart"
