//preference datums
#define NAME_CHAR_MAX 16
#define NAME_CHAR_MIN 2
#define FLAVOR_CHAR_LIMIT 256
#define LONG_FLAVOR_CHAR_LIMIT 2000

#define FULLNAME_MAX 50

//savefiles!
#define SAVEFILE_VERSION_MIN	3
#define SAVEFILE_VERSION_MAX	9
#define SAVEFILE_PROFILES_MAX	5
#define SAVEFILE_CLOUD_PROFILES_MAX	15

#define CUSTOMJOB_SAVEFILE_PROFILES_MAX	15
#define CUSTOMJOB_SAVEFILE_VERSION_MIN	1
#define CUSTOMJOB_SAVEFILE_VERSION_MAX	3

//human voice stuff
#define RANDOM_HUMAN_VOICE pick("1", "2", "3", "4")

#define PREFERRED_UPLINK_PDA "PDA"
#define PREFERRED_UPLINK_RADIO "Radio"
#define PREFERRED_UPLINK_STANDALONE "Standalone"
