// RANCH DEFINES

#define RANCH_STAGE_CHILD 0
#define RANCH_STAGE_ADULT 1
#define RANCH_STAGE_SENIOR 2

#define RANCH_PREFERENCE_NONE 0
#define RANCH_PREFERENCE_SAME 1
#define RANCH_PREFERENCE_DIFF 1<<1

#define FLEE_DISTANCE 5
#define MAX_FEED_TARGETS 5

#define FIGHT_PRIORITY 9
#define FLEE_PRIORITY 8
#define HUNGER_PRIORITY 7
#define EGG_PRIORITY 5
#define FOLLOW_PRIORITY 4
