#define ROLE_TRAITOR "traitor"
#define ROLE_SPY_THIEF "spy_thief"
#define ROLE_NUKEOP "nukeop"
#define ROLE_VAMPIRE "vampire"
#define ROLE_GANG_LEADER "gang_leader"
#define ROLE_WIZARD "wizard"
#define ROLE_CHANGELING "changeling"
#define ROLE_WEREWOLF "werewolf"
#define ROLE_BLOB "blob"
#define ROLE_WRAITH "wraith"
#define ROLE_HEAD_REV "head_rev"
#define ROLE_CONSPIRATOR "conspirator"
#define ROLE_ARCFIEND "arcfiend"
#define ROLE_FLOCKMIND "flockmind"
#define ROLE_FLOCKTRACE "flocktrace"
#define ROLE_MISC "misc"

// special antagonist roles
#define ROLE_GANG_MEMBER "gang_member"
#define ROLE_HUNTER "hunter"
#define ROLE_WRESTLER "wrestler"
#define ROLE_EMAGGED_ROBOT "emagged robot"
#define ROLE_SYNDICATE_ROBOT "syndicate robot"
#define ROLE_POLTERGEIST "poltergeist"
#define ROLE_PLAGUERAT "plaguerat"
#define ROLE_HARBINGERSUMMON "harbinger summon"
#define ROLE_HANDSPIDER "handspider"
#define ROLE_EYESPIDER "eyespider"
#define ROLE_LEGWORM "legworm"
#define ROLE_BUTTCRAB "buttcrab"
#define ROLE_VAMPTHRALL "vampthrall"
#define ROLE_SLEEPER_AGENT "sleeper agent"
#define ROLE_HARDMODE_TRAITOR "hard-mode traitor"
#define ROLE_MINDHACK "mindhack"
#define ROLE_NUKEOP_GUNBOT "nukeop gunbot"
#define ROLE_SALVAGER "salvager"
#define ROLE_ZOMBIE "zombie"

// gimmicks
#define ROLE_BATTLER "battler"
#define ROLE_OMNITRAITOR "omnitraitor"
#define ROLE_GRINCH "grinch"
#define ROLE_FLOOR_GOBLIN "floor_goblin"
#define ROLE_SLASHER "slasher"
