#define SAVEFILE_VERSION_MIN	3
#define SAVEFILE_VERSION_MAX	9
#define SAVEFILE_PROFILES_MAX	5

#define CUSTOMJOB_SAVEFILE_PROFILES_MAX	15
#define CUSTOMJOB_SAVEFILE_VERSION_MIN	1
#define CUSTOMJOB_SAVEFILE_VERSION_MAX	3
