//i am speed !!!
#define BASE_SPEED 1.7
#define BASE_SPEED_SUSTAINED 1.55
#define SPRINT_SCALING 0.12
#define SPRINT_SCALING_LYING 0.36
#define SPRINT_SCALING_STAGGER 0.64
#define WALK_DELAY_ADD 0.8
#define DIAG_MOVE_DELAY_MULT 1.4
