//i am speed !!!
#define BASE_SPEED 1.65
#define BASE_SPEED_SUSTAINED 1.5
#define RUN_SCALING 0.12
#define RUN_SCALING_LYING 0.2
#define RUN_SCALING_STAGGER 0.64
#define WALK_DELAY_ADD 0.8
#define DIAG_MOVE_DELAY_MULT 1.4
