/// e.g. clown
#define PAY_DUMBCLOWN 1
/// e.g. staffie
#define PAY_UNTRAINED 100
// e.g. miner
#define PAY_TRADESMAN 300
/// e.g. scientist
#define PAY_DOCTORATE 500
/// e.g. head
#define PAY_IMPORTANT 1000
/// e.g. captain
#define PAY_EXECUTIVE 1500
