#define TUTORIAL_BOX_SIZE 23
#define TUTORIAL_GROUP_SIZE (TUTORIAL_BOX_SIZE * 2) + 3 // 2 boxes + 2 cordons 1 seperating walls

#define TUTORIAL_GROUP_NUM_ROWS 5
#define TUTORIAL_GROUP_NUM_COLS 5

#define Z_LEVEL_TUTORIAL 1

#define STAGE_ERROR -1
#define STAGE_NOTSTARTED 1
#define STAGE_INPROGRESS 2
#define STAGE_FINISHED 3

#define TASK_ERROR -1
#define TASK_NOTSTARTED 1
#define TASK_INPROGRESS 2
#define TASK_FINISHED 3
