enableScripts: false

logFilters:
  ## DISABLED_BUILD_SCRIPTS
  - code: YN0004
    level: discard
  ## INCOMPATIBLE_OS - fsevents junk
  - code: YN0062
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

preferAggregateCacheInfo: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.4.0.cjs
