enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

preferAggregateCacheInfo: true

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.4.1.cjs
