compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

packageExtensions:
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: "*"
  eslint-plugin-sonarjs@*:
    dependencies:
      "@typescript-eslint/parser": ^7
      typescript: "*"

pnpEnableEsmLoader: false

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.9.1.cjs
