compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard
  - code: YN0002
    level: discard
    pattern: css-loader@*
  - code: YN0002
    level: discard
    pattern: url-loader@*

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.9.1.cjs
