//------------ Sayflags ------------//
#define SAYFLAG_PRIORITY_DEFAULT 0
#define SAYFLAG_PRIORITY_LOW -10
#define SAYFLAG_PRIORITY_PROCESS_LAST -1000


//------------ Speech Outputs ------------//
#define SPEECH_OUTPUT_PRIORITY_HIGH 10
#define SPEECH_OUTPUT_PRIORITY_DEFAULT 0


//------------ Speech Modifiers ------------//
#define SPEECH_MODIFIER_PRIORITY_PROCESS_FIRST 1000
#define SPEECH_MODIFIER_PRIORITY_VERY_HIGH 100
#define SPEECH_MODIFIER_PRIORITY_DEFAULT 0
#define SPEECH_MODIFIER_PRIORITY_MUTANTRACES -5
#define SPEECH_MODIFIER_PRIORITY_ACCENTS -10
#define SPEECH_MODIFIER_PRIORITY_VERY_LOW -100
#define SPEECH_MODIFIER_PRIORITY_PROCESS_LAST -1000


//------------ Speech Prefixes ------------//
#define SPEECH_PREFIX_PRIORITY_DEFAULT 0
#define SPEECH_PREFIX_PRIORITY_LOW -10


//------------ Listen Inputs ------------//
#define LISTEN_INPUT_PRIORITY_HIGH 10
#define LISTEN_INPUT_PRIORITY_DEFAULT 0
#define LISTEN_INPUT_PRIORITY_DISTORTED -20
#define LISTEN_INPUT_PRIORITY_GLOBAL -10


//------------ Listen Modifiers ------------//
#define LISTEN_MODIFIER_PRIORITY_VERY_HIGH 100
#define LISTEN_MODIFIER_PRIORITY_DEFAULT 0
