# Goonstation Documentation Publisher

name: Code Documentation

on:
  push:
    branches: master

jobs:
  documentation:
    name: Code Documentation
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          tools/ci/install_spaceman_dmm.sh dmdoc
          touch +secret/__secret.dme

      - name: Run dmdoc
        run: ~/dmdoc

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dmdoc
          SINGLE_COMMIT: true
