name: "Update Changelog"
on:
  push:
    branches:
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: github.repository == 'goonstation/goonstation'
    steps:
      - name: Get requirements.txt
        uses: actions/checkout@v4
        with:
          sparse-checkout: ".github"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install dependencies
        run: |
          pip install -r .github/workflows/requirements.txt

      - name: Update Changelog
        run: |
          python .github/update_changelog.py
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_PATH: strings/changelog.txt
          ASS_CHANGELOG_PATH: strings/ass_changelog.txt
          GIT_EMAIL: "65057909+robuddybot@users.noreply.github.com"
          GIT_NAME: "robuddybot"
